apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  namespace: fscl
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.1.0
  image: hub.docker.com/repository/docker/rabaul/fscl-kafka-connect:latest
  replicas: 1
  bootstrapServers: fscl-cluster-kafka-bootstrap.kafka:9092
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      # find ip by running "echo$(kubectl -n kube-system get svc registry -o jsonpath='{.spec.clusterIP})"
      image: 10.96.175.134/fscl-debezium-connect:latest
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.1.0.Final/debezium-connector-postgres-3.1.0.Final-plugin.tar.gz
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  namespace: fscl
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: process-db
    database.port: 5432
    database.user: ${secrets:process-db-credentials/FSCL:db_username}
    database.password: ${secrets:process-db-credentials/FSCL:db_password}
    database.dbname: process
    topic.prefix: process
    transforms: outbox
    transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
    transforms.outbox.route.topic.replacement: ${routedByValue}.events
    transforms.outbox.table.fields.additional.placement: type:header:eventType
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: fscl
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["process-db-credentials"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: fscl
subjects:
- kind: ServiceAccount
  name: debezium-connect-cluster-connect
roleRef:
  kind: Role
  name: connector-configuration-role
  apiGroup: rbac.authorization.k8s.io
