@startuml
'https://plantuml.com/component-diagram



node "devhost" {

    node minikube <<cluster>> {
        package fscl-process-service <<deployment>> {
            component "fscl-process-service" as svc <<pod>>
            component "fscl-process-db" as db <<pod>>
            8080 - [svc]
            [svc] - 5005
            [svc] --> 5432
            5432 - [db]
        }
    }

    [curl] --> 8080: NodePort
    [IntelliJ] -> 5005: port-forward
}






@enduml